name: Build TimeTrack

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    name: Build TimeTrack
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'App'
            platform:  'linux/amd64'
            output: 'Linux'
            os: 'ubuntu-latest'
            output_file: 'timetrack'
          - name: 'App'
            platform:  'windows/amd64'
            output: 'Windows.exe'
            os: 'ubuntu-latest'
            output_file: 'timetrack'
          - name: 'App'
            platform: 'darwin/universal'
            output: 'osx.pkg'
            os: 'macos-latest'
            output_file: 'timetrack.pkg'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: timetrack
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.21'

      - name: Rename Files
        run: mv ./build/bin/${{ matrix.build.output_file }} ./build/bin/TimeTrack-${{  github.ref_name }}-${{ matrix.build.output }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TimeTrack-${{  github.ref_name }}-${{ matrix.build.output }}
          path: ./build/bin/TimeTrack-${{  github.ref_name }}-${{ matrix.build.output }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./binaries
          pattern: TimeTrack-${{  github.ref_name }}*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{  github.ref_name }}
          body_path: CHANGELOG.md
          files: ./binaries/*